global:
 scrape_interval: 10s
scrape_configs:
 - job_name: 'temporalmetrics'
   metrics_path: /metrics
   scheme: http
   static_configs:
     # Cluster metrics target
     - targets:
         - 'temporal:8000'
       labels:
         group: 'server-metrics'
 - job_name: 'temporalsdkmetrics'
   metrics_path: /metrics
   scheme: http
   static_configs:
     - targets:
       - host.docker.internal:9464
       labels:
         group: 'sdk-metrics'
