{
 "title": "Temporal 2",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Workflows completed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(temporal_workflow_completed[1m])"
    }
   ]
  },
  {
   "title": "Activities failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(temporal_activity_execution_failed[1m])"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "temporal_activity_execution_failed"
    }
   ]
  },
  {
   "title": "Workflows failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(temporal_workflow_failed[1m])"
    }
   ]
  }
 ]
}